In [8]:
import numpy as np
#vector initialized with small letter
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#creating a numpy array
#matrices initialized with capital letter
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #array of type int
print(A)

A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float) #array of type float
print(A)

A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex) #array of complex numbers
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [12]:
#Arrays of zeros and ones
z_array = np.zeros((2,3), dtype = int) #here default data type is float
print(z_array)

o_array = np.ones((2,3))

[[0 0 0]
 [0 0 0]]
