In [8]:
import numpy as np
#vector initialized with small letter
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#creating a numpy array
#matrices initialized with capital letter
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #array of type int
print(A)

A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float) #array of type float
print(A)

A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = complex) #array of complex numbers
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [15]:
#Arrays of zeros and ones
z_array = np.zeros((2,3), dtype = int) #here default data type is float
print(z_array)

o_array = np.ones((2,3), dtype = int)
print(o_array)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [31]:
#using arange and shape
A = np.arange(12)
print('A =',A)

B = np.arange(12).reshape(3,4)
print('B = ',B)

#giving -1 automatically adjust the size with given number of rows
print('B = ',B.reshape(2,-1))

#given number of elements are similar
print('B = ',B.reshape(*A.shape))

A = [ 0  1  2  3  4  5  6  7  8  9 10 11]
B =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B =  [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
B =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
#Adding two matrices
A = np.array([[1,2,3,],[4,5,6]], dtype = int)
B = np.array([[1,2,4],[6,7,8]], dtype = float)

C = A+B
print("A + B = ",C)

BB.reshape(3,2)

#multiplying two matrices
C = A.dot(B)
print("A * B = ",C)

A + B =  [[ 2.  4.  7.]
 [10. 12. 14.]]
[[1. 2. 4.]
 [6. 7. 8.]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)