In [42]:
#single for loop to recursion
def recursivePrint(m, n):
    if(m >= n):
        return
    
    print(m,end=' ')
    recursivePrint(m+1,n)

def iterativePrint(n):
    for x in range(n):
        print(x, end = ' ')

In [43]:
print("Iterative Print")
iterativePrint(10)

print("\nRecursive Print")
recursivePrint(0,10)

Iterative Print
0 1 2 3 4 5 6 7 8 9 
Recursive Print
0 1 2 3 4 5 6 7 8 9 

In [44]:
#double for loop to recursion
def recursivePrint(m, n, sizem, sizen):
    if m >= sizem or n > sizen:
        return
    
    elif n == sizen:
        recursivePrint(m+1,0,sizem,sizen)
    
    else:
        print("(",m, n, ")",end = ' ')
        recursivePrint(m,n+1,sizem,sizen)

def iterativePrint(m, n):
    for x in range(m):
        for y in range(n):
            print("(",x, y, ")",end = ' ')

In [45]:
print("Iterative Print")
iterativePrint(10,10)

print("\nRecursive Print")
recursivePrint(0,0,10,10)

Iterative Print
( 0 0 ) ( 0 1 ) ( 0 2 ) ( 0 3 ) ( 0 4 ) ( 0 5 ) ( 0 6 ) ( 0 7 ) ( 0 8 ) ( 0 9 ) ( 1 0 ) ( 1 1 ) ( 1 2 ) ( 1 3 ) ( 1 4 ) ( 1 5 ) ( 1 6 ) ( 1 7 ) ( 1 8 ) ( 1 9 ) ( 2 0 ) ( 2 1 ) ( 2 2 ) ( 2 3 ) ( 2 4 ) ( 2 5 ) ( 2 6 ) ( 2 7 ) ( 2 8 ) ( 2 9 ) ( 3 0 ) ( 3 1 ) ( 3 2 ) ( 3 3 ) ( 3 4 ) ( 3 5 ) ( 3 6 ) ( 3 7 ) ( 3 8 ) ( 3 9 ) ( 4 0 ) ( 4 1 ) ( 4 2 ) ( 4 3 ) ( 4 4 ) ( 4 5 ) ( 4 6 ) ( 4 7 ) ( 4 8 ) ( 4 9 ) ( 5 0 ) ( 5 1 ) ( 5 2 ) ( 5 3 ) ( 5 4 ) ( 5 5 ) ( 5 6 ) ( 5 7 ) ( 5 8 ) ( 5 9 ) ( 6 0 ) ( 6 1 ) ( 6 2 ) ( 6 3 ) ( 6 4 ) ( 6 5 ) ( 6 6 ) ( 6 7 ) ( 6 8 ) ( 6 9 ) ( 7 0 ) ( 7 1 ) ( 7 2 ) ( 7 3 ) ( 7 4 ) ( 7 5 ) ( 7 6 ) ( 7 7 ) ( 7 8 ) ( 7 9 ) ( 8 0 ) ( 8 1 ) ( 8 2 ) ( 8 3 ) ( 8 4 ) ( 8 5 ) ( 8 6 ) ( 8 7 ) ( 8 8 ) ( 8 9 ) ( 9 0 ) ( 9 1 ) ( 9 2 ) ( 9 3 ) ( 9 4 ) ( 9 5 ) ( 9 6 ) ( 9 7 ) ( 9 8 ) ( 9 9 ) 
Recursive Print
( 0 0 ) ( 0 1 ) ( 0 2 ) ( 0 3 ) ( 0 4 ) ( 0 5 ) ( 0 6 ) ( 0 7 ) ( 0 8 ) ( 0 9 ) ( 1 0 ) ( 1 1 ) ( 1 2 ) ( 1 3 ) ( 1 4 ) ( 1 5 ) ( 1 6 ) ( 1 7 ) ( 1 8 ) ( 1 9 ) ( 2 0 )

In [85]:
#knight's tour problem
from numpy import matrix
def createBoardAndMovements(n):
    board = [[-1 for x in range(n)]for x in range(n)]
#     x_moves = [2, 1, -1, -2, -2, -1, 1, 2]
#     y_moves = [1, 2, 2, 1, -1, -2, -2, -1]
    knight_movements = [[2,1],[1,2],[-1,2],[-2,1],[-2,-1],[-1,-2],[1,-2],[2,-1]]
#     print(matrix(board))
    return board, knight_movements

In [86]:
board, movements = createBoardAndMovements(5)
x, y = 0, 0
board[0][0] = 0
pos = 1

In [87]:
def isMoveSafe(n, x, y, board):
    if(x >= 0 and y >= 0 and x < n and y < n and board[x][y] == -1):
        return True
    else:
        return False

In [88]:
def knightsTour(n,x,y,movements,board,pos):
    if pos == n**2:
        return True

    for i in movements:
        x_move = i[0]
        y_move = i[1]
        if isMoveSafe(n,x+x_move,y+y_move,board):
            board[x+x_move][y+y_move] = pos
            if knightsTour(n,x+x_move,y+y_move,movements,board,pos+1):
                return True
                
            board[x+x_move][y+y_move] = -1
    return False

In [89]:
knightsTour(5,0,0,movements,board,1)

True

In [90]:
print(matrix(board))

[[ 0  5 14  9 20]
 [13  8 19  4 15]
 [18  1  6 21 10]
 [ 7 12 23 16  3]
 [24 17  2 11 22]]


In [32]:
#N-Queens problem
def isValidPos(n, x, y, board):
#     for i in range(y):
#         if board[i][y] != -1:
#             return False
    for j in range(y):
        if board[x][j] != -1:
            return False 
    
#     checking for upper diagonal
    for i,j in zip(range(x,-1,-1),range(y,-1,-1)):
        if board[i][j] != -1:
            return False
    
#     checking for lower diagonal
    for i,j in zip(range(x,n,1),range(y,-1,-1)):
        if board[i][j] != -1:
            return False
    
    return True

In [36]:
def nQueens(n, y, board, pos):
    if pos > n:
        return True
    for x in range(n):
        if isValidPos(n,x,y,board):
            board[x][y] = pos
            if nQueens(n, y+1, board, pos+1):
                return True
            
            board[x][y] = -1
    return False

In [37]:
from numpy import matrix
def createBoard(n):
    return [[-1 for x in range(n)]for x in range(n)]
board = createBoard(4)    
pos = 1
nQueens(4,0,board,pos)
print(matrix(board))

[[-1 -1  3 -1]
 [ 1 -1 -1 -1]
 [-1 -1 -1  4]
 [-1  2 -1 -1]]


In [1]:
#sudoku solver
def isVaildNum(n, xpos, ypos, num, board):
    #not in same row
    for x in range(n):
        if board[x][ypos] == num:
            return False
        
    #not in same column
    for y in range(n):
        if board[xpos][y] == num:
            return False
    
    #not is same sub-box
    #coordinates for which sub-box to look
    x0 = (xpos//3)*3
    y0 = (ypos//3)*3
    for x in range(3):
        for y in range(3):
            if board[x+x0][y+y0] == num:
                return False
    
    return True

In [2]:
def sudokuSolver(n, board):
    for x in range(n):
        for y in range(n):
            if board[x][y] == 0:
                for num in range(1,10):
                    if isVaildNum(n,x,y,num,board):
                        board[x][y] = num
                        if sudokuSolver(n, board):
                            return True
                        
                        board[x][y] = 0
    return False

In [3]:
board = [[3, 0, 6, 5, 0, 8, 4, 0, 0], 
          [5, 2, 0, 0, 0, 0, 0, 0, 0], 
          [0, 8, 7, 0, 0, 0, 0, 3, 1], 
          [0, 0, 3, 0, 1, 0, 0, 8, 0], 
          [9, 0, 0, 8, 6, 3, 0, 0, 5], 
          [0, 5, 0, 0, 9, 0, 6, 0, 0], 
          [1, 3, 0, 0, 0, 0, 2, 5, 0], 
          [0, 0, 0, 0, 0, 0, 0, 7, 4], 
          [0, 0, 5, 2, 0, 6, 3, 0, 0]] 
n = 9
sudokuSolver(n,board)

In [4]:
from numpy import matrix
print(matrix(board))

[[3 0 6 5 0 8 4 0 0]
 [5 2 0 0 0 0 0 0 0]
 [0 8 7 0 0 0 0 3 1]
 [0 0 3 0 1 0 0 8 0]
 [9 0 0 8 6 3 0 0 5]
 [0 5 0 0 9 0 6 0 0]
 [1 3 0 0 0 0 2 5 0]
 [0 0 0 0 0 0 0 7 4]
 [0 0 5 2 0 6 3 0 0]]
