In [60]:
sortedMatrix = [ [10, 20, 30, 40], 
        [15, 25, 35, 45], 
        [27, 29, 37, 48], 
        [32, 33, 39, 50] ] 

In [63]:
from numpy import matrix
print(matrix(sortedMatrix))

[[10 20 30 40]
 [15 25 35 45]
 [27 29 37 48]
 [32 33 39 50]]


In [64]:
def searchInSortedMatrix(num, row, col):
    global sortedMatrix
    
    if row >= len(sortedMatrix) or col >= len(sortedMatrix[0]):
        return
    
    if sortedMatrix[row][col] == num :
        print(row, col)
        return
    
    elif sortedMatrix[row][col] < num:
        searchInSortedMatrix(num, row + 1, col)
    
    else:
        searchInSortedMatrix(num, row, col - 1)

In [65]:
row = 0
col = len(sortedMatrix[0]) - 1
searchInSortedMatrix(48, row, col)

2 3
