In [4]:
sudokuProblem = [[3, 0, 6, 5, 0, 8, 4, 0, 0], 
          [5, 2, 0, 0, 0, 0, 0, 0, 0], 
          [0, 8, 7, 0, 0, 0, 0, 3, 1], 
          [0, 0, 3, 0, 1, 0, 0, 8, 0], 
          [9, 0, 0, 8, 6, 3, 0, 0, 5], 
          [0, 5, 0, 0, 9, 0, 6, 0, 0], 
          [1, 3, 0, 0, 0, 0, 2, 5, 0], 
          [0, 0, 0, 0, 0, 0, 0, 7, 4], 
          [0, 0, 5, 2, 0, 6, 3, 0, 0]]

print(sudokuProblem)

[[3, 0, 6, 5, 0, 8, 4, 0, 0], [5, 2, 0, 0, 0, 0, 0, 0, 0], [0, 8, 7, 0, 0, 0, 0, 3, 1], [0, 0, 3, 0, 1, 0, 0, 8, 0], [9, 0, 0, 8, 6, 3, 0, 0, 5], [0, 5, 0, 0, 9, 0, 6, 0, 0], [1, 3, 0, 0, 0, 0, 2, 5, 0], [0, 0, 0, 0, 0, 0, 0, 7, 4], [0, 0, 5, 2, 0, 6, 3, 0, 0]]


In [5]:
from numpy import matrix
print(matrix(sudokuProblem))

[[3 0 6 5 0 8 4 0 0]
 [5 2 0 0 0 0 0 0 0]
 [0 8 7 0 0 0 0 3 1]
 [0 0 3 0 1 0 0 8 0]
 [9 0 0 8 6 3 0 0 5]
 [0 5 0 0 9 0 6 0 0]
 [1 3 0 0 0 0 2 5 0]
 [0 0 0 0 0 0 0 7 4]
 [0 0 5 2 0 6 3 0 0]]


In [6]:
def isValid(y, x, n):
    global sudokuProblem
    for i in range(9):
        if sudokuProblem[y][i] == n:
            return False
    for j in range(9):
        if sudokuProblem[i][x] == n:
            return False
    
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sudokuProblem[y0+i][x0+j] == n:
                return False
    return True


In [7]:
def sudokuSolver():
    global sudokuProblem
    for y in range(9):
        for x in range(9):
            if sudokuProblem[y][x] == 0:
                for n in range(1,10):
                    if isValid(y,x,n):
                        sudokuProblem[y][x] = n
                        sudokuSolver()
                        sudokuProblem[y][x] = 0
                return
    print(matrix(sudokuProblem))
    input()

In [ ]:
sudokuSolver()

[[3 1 6 5 7 8 4 2 9]
 [5 2 4 1 3 9 6 7 8]
 [9 8 7 4 6 2 5 3 1]
 [2 6 3 4 1 5 7 8 9]
 [9 1 7 8 6 3 2 4 5]
 [4 5 8 7 9 2 6 1 3]
 [1 3 4 7 8 9 2 5 6]
 [2 6 8 1 3 5 9 7 4]
 [7 9 5 2 4 6 3 1 8]]
